### <center>San Jose State University<br>Department of Applied Data Science</center>
#  <center>DATA 220<br>Mathematical Methods for Data Analysis</center>
### <center>Fall 2020<br>Instructor: Ron Mak</center>
#  <center>Assignment #11<br>Matrix Operations Problem Set</center>
#### <center>100 points total (20 points each)<br><br>Work together with your lab partner.<br>Write your solutions in one or more cells after each problem.<br>Whenever possible, use matrix operations and not loops.<br>You can add your own functions or other support code.</center>
#### <center>Due November 19, 2020</center>

#### <strong>PROBLEM 1.</strong> Amalgamated Widgets, Inc. manufactures several products using various amounts of materials per product:
<table>
    <tr>
        <th>Product</th>
        <th>Metal</th>
        <th>Wood</th>
        <th>Plastic</th>
        <th>Cloth</th>
        <th>Paper</th>
    </tr>
    <tr>
        <td>A</td><td>0</td><td>1.3</td><td>0.2</td><td>0.8</td><td>0.4</td>
    </tr>
    <tr>
        <td>B</td><td>0</td><td>0</td><td>1.5</td><td>0.4</td><td>0.3</td>
    </tr>
    <tr>
        <td>C</td><td>0.25</td><td>0</td><td>0</td><td>0.2</td><td>0.7</td>
    </tr>
    <tr>
        <td>D</td><td>0</td><td>0</td><td>0.3</td><td>0.7</td><td>0.5</td>
    </tr>
    <tr>
        <td>E</td><td>0.15</td><td>0</td><td>0.5</td><td>0.4</td><td>0.8</td>
    </tr>
</table>

#### On a certain day, the following total amounts of materials were used:
<table>
    <tr>
        <th>Metal</th>
        <th>Wood</th>
        <th>Plastic</th>
        <th>Cloth</th>
        <th>Paper</th>
    </tr>
    <tr>
        <td>51.0</td><td>312.0</td><td>215.4</td><td>373.1</td><td>356.0</td>
    </tr>
</table>

#### How many of each product were made that day?

In [3]:
import numpy as np

x1s = [   0,       0,    0.25,       0,  0.15]  # Metal
x2s = [ 1.3,       0,       0,       0,     0]  # Wood
x3s = [ 0.2,     1.5,       0,     0.3,   0.5]  # Plastic
x4s = [ 0.8,     0.4,     0.2,     0.7,   0.4]  # Cloth
x5s = [ 0.4,     0.3,     0.7,     0.5,   0.8]  # Paper
ys  = [51.0,   312.0,    215.4,  373.1, 356.0]  # Quantities 


x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)



In [4]:
n        = len(ys)
sum_x1   = np.sum(x1)
sum_x2   = np.sum(x2)
sum_x3   = np.sum(x3)
sum_x4   = np.sum(x4)
sum_x5   = np.sum(x5)

sum_y    = np.sum(y)
sum_x1y  = np.sum(x1*y)
sum_x2y  = np.sum(x2*y)
sum_x3y  = np.sum(x3*y)
sum_x4y  = np.sum(x4*y)
sum_x5y  = np.sum(x5*y)


sum_x1x1 = np.sum(x1*x1)
sum_x2x2 = np.sum(x2*x2)
sum_x3x3 = np.sum(x3*x3)
sum_x4x4 = np.sum(x4*x4)
sum_x5x5 = np.sum(x5*x5)

sum_x1x2 = np.sum(x1*x2)
sum_x1x3 = np.sum(x1*x3)
sum_x1x4 = np.sum(x1*x4)
sum_x1x5 = np.sum(x1*x5)

sum_x2x3 = np.sum(x2*x3)
sum_x2x4 = np.sum(x2*x4)
sum_x2x5 = np.sum(x2*x5)

sum_x3x4 = np.sum(x3*x4)
sum_x3x5 = np.sum(x3*x5)

sum_x4x5 = np.sum(x4*x5)


n, sum_x1, sum_x2, sum_x3, sum_x4, sum_x5, sum_y, sum_x1y, sum_x2y, sum_x3y, sum_x4y, sum_x5y, sum_x1x1, sum_x2x2,sum_x3x3, sum_x4x4, sum_x5x5,  sum_x1x2, sum_x1x3, sum_x1x4, sum_x1x5, sum_x2x3, sum_x2x4, sum_x2x5, sum_x3x4, sum_x3x5, sum_x4x5

(5,
 0.4,
 1.3,
 2.5,
 2.5,
 2.7,
 1307.5,
 107.25,
 66.3,
 768.13,
 612.25,
 736.13,
 0.08499999999999999,
 1.6900000000000002,
 2.63,
 1.4900000000000002,
 1.6300000000000001,
 0.0,
 0.075,
 0.11,
 0.295,
 0.26,
 1.04,
 0.52,
 1.1700000000000002,
 1.08,
 1.25)

In [52]:
#eqn1 = np.array([n, sum_x1, sum_x2, sum_x3, sum_x4, sum_x5, sum_y])
#eqn2 = np.array([sum_x1, sum_x1x1, sum_x1x2, sum_x1x3, sum_x1x4, sum_x1x5, sum_x1y])
#eqn3 = np.array([sum_x2, sum_x1x2, sum_x2x3, sum_x2x4, sum_x2x5, sum_x2x2, sum_x2y])
#eqn4 = np.array([sum_x3, sum_x1x3, sum_x2x3, sum_x3x4, sum_x3x5, sum_x3x3, sum_x3y])
#eqn5 = np.array([sum_x4, sum_x1x4, sum_x2x4, sum_x3x4, sum_x4x5, sum_x4x4, sum_x4y])
#eqn6 = np.array([sum_x5, sum_x1x5, sum_x2x5, sum_x3x5, sum_x4x5, sum_x5x5, sum_x5y])

eqn1 = np.array([n, sum_x1, sum_x2, sum_x3, sum_x4, sum_x5, sum_y])
eqn2 = np.array([sum_x1, sum_x1x1, sum_x1x2, sum_x1x3, sum_x1x4, sum_x1x5, sum_x1y])
eqn3 = np.array([sum_x2, sum_x1x2, sum_x2x2, sum_x2x3, sum_x2x4, sum_x2x5, sum_x2y])
eqn4 = np.array([sum_x3, sum_x1x3, sum_x2x3, sum_x3x3, sum_x3x4, sum_x3x5, sum_x3y])
eqn5 = np.array([sum_x4, sum_x1x4, sum_x2x4, sum_x3x4, sum_x4x4, sum_x4x5, sum_x4y])
eqn6 = np.array([sum_x5, sum_x1x5, sum_x2x5, sum_x3x5, sum_x4x5, sum_x5x5, sum_x5y])


eqn1, eqn2, eqn3, eqn4, eqn5, eqn6

(array([5.000e+00, 4.000e-01, 1.300e+00, 2.500e+00, 2.500e+00, 2.700e+00,
        1.308e+03]),
 array([4.000e-01, 8.500e-02, 0.000e+00, 7.500e-02, 1.100e-01, 2.950e-01,
        1.072e+02]),
 array([ 1.3 ,  0.  ,  1.69,  0.26,  1.04,  0.52, 66.3 ]),
 array([2.500e+00, 7.500e-02, 2.600e-01, 2.630e+00, 1.170e+00, 1.080e+00,
        7.681e+02]),
 array([2.500e+00, 1.100e-01, 1.040e+00, 1.170e+00, 1.490e+00, 1.250e+00,
        6.122e+02]),
 array([2.700e+00, 2.950e-01, 5.200e-01, 1.080e+00, 1.250e+00, 1.630e+00,
        7.361e+02]))

In [53]:
import numpy as np

A = np.array([[5.0000e+00, 4.0000e-01, 1.3000e+00, 2.5000e+00, 2.5000e+00, 2.7000e+00],
              [4.0000e-01, 8.5000e-02, 0.0000e+00, 7.5000e-02, 1.1000e-01, 2.9500e-01],
              [ 1.3 ,  0.  ,  0.26,  1.04,  0.52,  1.69],
              [2.5000e+00, 7.5000e-02, 2.6000e-01, 1.1700e+00, 1.0800e+00, 2.6300e+00],
              [2.5000e+00, 1.1000e-01, 1.0400e+00, 1.1700e+00, 1.2500e+00, 1.4900e+00],
              [2.7000e+00, 2.9500e-01, 5.2000e-01, 1.0800e+00, 1.2500e+00, 1.6300e+00]
             ])


b = np.array([1.3075e+03, 1.0725e+02, 66.3, 7.6813e+02, 6.1225e+02, 7.3613e+02])

#Ainv = np.linalg.inv(A)

#solution = np.linalg.solve(Ainv, b)
solution = np.linalg.inv(A)@b


print(f'β0 = {solution[0]:9,.2f}')
print(f'β1 = {solution[1]:9,.2f}')
print(f'β2 = {solution[2]:9,.2f}')
print(f'β3 = {solution[3]:9,.2f}')
print(f'β4 = {solution[4]:9,.2f}')
print(f'β5 = {solution[5]:9,.2f}')


β0 =  1,293.54
β1 = -2,426.11
β2 =   -624.76
β3 =   -532.12
β4 =   -365.59
β5 =   -419.73


#### <strong>PROBLEM 2.</strong> Find the least-squares regression line for the points (1,1), (2,2), (3,4), (4,4), and (5,6) using the matrix form of the normal equations <em>A.T</em>@<em>A</em>@<strong>x</strong> = <em>A.T</em>@<strong>b</strong>.

In [7]:
import numpy as np

xs = [1,2,3,4,5]
ys = [1,2,4,4,6]

b = np.array(ys)
ones = np.array([1 for _ in range(len(xs))])

In [8]:
A = np.array([ones, np.array(xs)]).T
A

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5]])

In [9]:
A.T

array([[1, 1, 1, 1, 1],
       [1, 2, 3, 4, 5]])

In [10]:
ATA = A.T@A
ATA

array([[ 5, 15],
       [15, 55]])

In [11]:
from numpy.linalg import inv
%precision 3

ATAinv = inv(ATA)
ATAinv

array([[ 1.1, -0.3],
       [-0.3,  0.1]])

In [12]:
ATb = A.T@b
ATb

array([17, 63])

In [13]:
xhat = ATAinv@ATb
xhat

array([-0.2,  1.2])

Therefore, b = -0.2 and m = 1.2

#### <strong>PROBLEM 3.</strong> The following table shows the mean distances <em>x</em> in astonomical units (multiples of the distance between the sun and the earth) and the periods <em>y</em> in years (how many earth-years to orbit the sun):
<table>
    <tr>
        <th>Planet</th>
        <th>Mercury</th>
        <th>Venus</th>
        <th>Earth</th>
        <th>Mars</th>
        <th>Jupiter</th>
        <th>Saturn</th>
    </tr>
    <tr>
        <td>Distance </em>x</em></td><td>0.387</td><td>0.723</td><td>1.000</td><td>1.524</td><td>5.203</td><td>9.537</td>
    </tr>
    <tr>
        <td>Years </em>y</em></td><td>0.241</td><td>0.615</td><td>1.000</td><td>1.881</td><td>11.862</td><td>29.457</td>
    </tr>
</table>

#### It turns out that if you take the natural logarithm of the numbers in the table, the transformed points lie roughly in a straight line. Find the least-squares regression line using the matrix form of the normal equations <em>A.T</em>@<em>A</em>@<strong>x</strong> = <em>A.T</em>@<strong>b</strong>. 

In [14]:
import numpy as np

xs = [0.387,0.723,1.000,1.524,5.203,9.537]
ys = [0.241,0.615,1.000,1.881,11.862,29.457]

b = np.array(ys)
ones = np.array([1 for _ in range(len(xs))])

In [15]:
A = np.array([ones, np.array(xs)]).T
A

array([[1.   , 0.387],
       [1.   , 0.723],
       [1.   , 1.   ],
       [1.   , 1.524],
       [1.   , 5.203],
       [1.   , 9.537]])

In [16]:
A.T

array([[1.   , 1.   , 1.   , 1.   , 1.   , 1.   ],
       [0.387, 0.723, 1.   , 1.524, 5.203, 9.537]])

In [17]:
ATA = A.T@A
ATA

array([[  6.   ,  18.374],
       [ 18.374, 122.021]])

In [18]:
from numpy.linalg import inv
%precision 3

ATAinv = inv(ATA)
ATAinv

array([[ 0.309, -0.047],
       [-0.047,  0.015]])

In [19]:
ATb = A.T@b
ATb

array([ 45.056, 347.054])

In [20]:
xhat = ATAinv@ATb
xhat

array([-2.228,  3.18 ])

#### <strong>PROBLEM 4.a.</strong> Here's more data about that certain day at Amalgamated Widgets, Inc. There are three more products and the cost  to make one of each product.
<table>
    <tr>
        <th>Product</th>
        <th>Metal</th>
        <th>Wood</th>
        <th>Plastic</th>
        <th>Cloth</th>
        <th>Paper</th>
        <th>Cost</th>
    </tr>
    <tr>
        <td>A</td><td>0</td><td>1.3</td><td>0.2</td><td>0.8</td><td>0.4</td><td>21.60</td>
    </tr>
    <tr>
        <td>B</td><td>0</td><td>0</td><td>1.5</td><td>0.4</td><td>0.3</td><td>17.20</td>
    </tr>
    <tr>
        <td>C</td><td>0.25</td><td>0</td><td>0</td><td>0.2</td><td>0.7</td><td>4.70</td>
    </tr>
    <tr>
        <td>D</td><td>0</td><td>0</td><td>0.3</td><td>0.7</td><td>0.5</td><td>9.60</td>
    </tr>
    <tr>
        <td>E</td><td>0.15</td><td>0</td><td>0.5</td><td>0.4</td><td>0.8</td><td>15.70</td>
    </tr>
    <tr>
        <td>F</td><td>1.00</td><td>0.90</td><td>0.00</td><td>0.65</td><td>0.00</td><td>26.80</td>
    </tr>
    <tr>
        <td>G</td><td>0.22</td><td>0.00</td><td>1.80</td><td>1.00</td><td>1.25</td><td>25.50</td>
    </tr>
    <tr>
        <td>H</td><td>0.20</td><td>0.75</td><td>0.65</td><td>1.00</td><td>1.25</td><td>22.40</td>
    </tr>
</table>

#### The manufacturing cost of a product is related to the amounts of materials used to make the product. Find the least-squares regression line using the matrix form of the normal equations <em>A.T</em>@<em>A</em>@<strong>x</strong> = <em>A.T</em>@<strong>b</strong> that will compute an estimated manufacturing cost of a product.

In [21]:
import numpy as np
from numpy.linalg import inv
%precision 3

'%.3f'

In [22]:
x1s = [     0, 0, 0.25, 0, 0.15, 1.00, 0.22, 0.20]  # Metal
x2s = [   1.3, 0, 0, 0, 0, 0.90, 0.00, 0.75]  # Wood
x3s = [   0.2, 1.5, 0, 0.3, 0.5, 0.00, 1.80, 0.65]  # Plastic
x4s = [   0.8, 0.4, 0.2, 0.7, 0.4, 0.65, 1.00, 1.00]  # Cloth
x5s = [   0.4, 0.3, 0.7, 0.5, 0.8, 0.00, 1.25, 1.25]  # Paper
ys  = [ 21.60, 17.20, 4.70, 9.60, 15.70, 26.80, 25.50, 22.40]  # Cost

x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)

In [23]:
ones = np.array([1, 1, 1, 1, 1, 1, 1, 1])
A = np.array([ones, x1, x2, x3, x4, x5]).T
A

array([[1.  , 0.  , 1.3 , 0.2 , 0.8 , 0.4 ],
       [1.  , 0.  , 0.  , 1.5 , 0.4 , 0.3 ],
       [1.  , 0.25, 0.  , 0.  , 0.2 , 0.7 ],
       [1.  , 0.  , 0.  , 0.3 , 0.7 , 0.5 ],
       [1.  , 0.15, 0.  , 0.5 , 0.4 , 0.8 ],
       [1.  , 1.  , 0.9 , 0.  , 0.65, 0.  ],
       [1.  , 0.22, 0.  , 1.8 , 1.  , 1.25],
       [1.  , 0.2 , 0.75, 0.65, 1.  , 1.25]])

In [24]:
ATA = A.T@A
ATA

array([[8.   , 1.82 , 2.95 , 4.95 , 5.15 , 5.2  ],
       [1.82 , 1.173, 1.05 , 0.601, 1.18 , 0.82 ],
       [2.95 , 1.05 , 3.062, 0.748, 2.375, 1.458],
       [4.95 , 0.601, 0.748, 6.293, 3.62 , 4.143],
       [5.15 , 1.18 , 2.375, 3.62 , 3.913, 3.75 ],
       [5.2  , 0.82 , 1.458, 4.143, 3.75 , 4.755]])

In [25]:
b = y
ATb = A.T@b
ATb

array([143.5  ,  40.42 ,  69.   , 101.31 , 103.42 ,  94.325])

In [26]:
ATAinv = inv(ATA)
ATAinv

array([[ 1.008, -0.494, -0.037, -0.087, -0.752, -0.337],
       [-0.494,  1.678,  0.027,  0.221, -0.511,  0.453],
       [-0.037,  0.027,  1.493,  0.574, -2.102,  0.736],
       [-0.087,  0.221,  0.574,  0.639, -1.001,  0.113],
       [-0.752, -0.511, -2.102, -1.001,  5.226, -1.695],
       [-0.337,  0.453,  0.736,  0.113, -1.695,  1.513]])

In [27]:
xhat = ATAinv@ATb
xhat

array([ 3.767, 11.081,  8.961,  8.015,  5.609, -0.347])

In [28]:
A@xhat

array([21.368, 17.93 ,  7.417,  9.925, 11.403, 26.56 , 25.808, 23.09 ])

In [29]:
b

array([21.6, 17.2,  4.7,  9.6, 15.7, 26.8, 25.5, 22.4])

In [30]:
for i,z in enumerate(b):
    print(f'β{i} = {b[i]}')

β0 = 21.6
β1 = 17.2
β2 = 4.7
β3 = 9.6
β4 = 15.7
β5 = 26.8
β6 = 25.5
β7 = 22.4


#### <strong>PROBLEM 4.b.</strong> Find the least-squares regression line for the same data using <em>QR</em> factorization. Verify that matrix <em>R</em> is upper-triangular and invertible. Verify that the columns of matrix <em>Q</em> are orthonormal. 

In [31]:
import numpy as np
from numpy.linalg import inv, qr

In [32]:
x1s = [     0, 0, 0.25, 0, 0.15, 1.00, 0.22, 0.20]  # Metal
x2s = [   1.3, 0, 0, 0, 0, 0.90, 0.00, 0.75]  # Wood
x3s = [   0.2, 1.5, 0, 0.3, 0.5, 0.00, 1.80, 0.65]  # Plastic
x4s = [   0.8, 0.4, 0.2, 0.7, 0.4, 0.65, 1.00, 1.00]  # Cloth
x5s = [   0.4, 0.3, 0.7, 0.5, 0.8, 0.00, 1.25, 1.25]  # Paper
ys  = [ 21.60, 17.20, 4.70, 9.60, 15.70, 26.80, 25.50, 22.40]  # Cost

x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)

In [33]:
ones = np.array([1, 1, 1, 1, 1, 1, 1, 1])
A = np.array([ones, x1, x2, x3, x4, x5]).T
A

array([[1.  , 0.  , 1.3 , 0.2 , 0.8 , 0.4 ],
       [1.  , 0.  , 0.  , 1.5 , 0.4 , 0.3 ],
       [1.  , 0.25, 0.  , 0.  , 0.2 , 0.7 ],
       [1.  , 0.  , 0.  , 0.3 , 0.7 , 0.5 ],
       [1.  , 0.15, 0.  , 0.5 , 0.4 , 0.8 ],
       [1.  , 1.  , 0.9 , 0.  , 0.65, 0.  ],
       [1.  , 0.22, 0.  , 1.8 , 1.  , 1.25],
       [1.  , 0.2 , 0.75, 0.65, 1.  , 1.25]])

In [34]:
A

array([[1.  , 0.  , 1.3 , 0.2 , 0.8 , 0.4 ],
       [1.  , 0.  , 0.  , 1.5 , 0.4 , 0.3 ],
       [1.  , 0.25, 0.  , 0.  , 0.2 , 0.7 ],
       [1.  , 0.  , 0.  , 0.3 , 0.7 , 0.5 ],
       [1.  , 0.15, 0.  , 0.5 , 0.4 , 0.8 ],
       [1.  , 1.  , 0.9 , 0.  , 0.65, 0.  ],
       [1.  , 0.22, 0.  , 1.8 , 1.  , 1.25],
       [1.  , 0.2 , 0.75, 0.65, 1.  , 1.25]])

In [35]:
Q,R = qr(A)
R

array([[-2.828, -0.643, -1.043, -1.75 , -1.821, -1.838],
       [ 0.   ,  0.871,  0.435, -0.603,  0.01 , -0.417],
       [ 0.   ,  0.   ,  1.336, -0.611,  0.353, -0.209],
       [ 0.   ,  0.   ,  0.   ,  1.579,  0.415,  0.346],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.548,  0.614],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.813]])

We can see that matrix R is also invertible

In [37]:
Rinv = inv(R)
Rinv

array([[-3.536e-01, -2.611e-01, -1.910e-01, -5.653e-01, -6.191e-01,
        -2.740e-01],
       [ 0.000e+00,  1.148e+00, -3.734e-01,  2.936e-01, -1.692e-03,
         3.685e-01],
       [ 0.000e+00,  0.000e+00,  7.483e-01,  2.893e-01, -7.007e-01,
         5.983e-01],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  6.332e-01, -4.789e-01,
         9.219e-02],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  1.824e+00,
        -1.378e+00],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
         1.230e+00]])

In [38]:
Q

array([[-0.354, -0.261,  0.782, -0.063, -0.167, -0.088],
       [-0.354, -0.261, -0.191,  0.385, -0.608, -0.318],
       [-0.354,  0.026, -0.284, -0.492, -0.255,  0.404],
       [-0.354, -0.261, -0.191, -0.375,  0.514, -0.596],
       [-0.354, -0.089, -0.247, -0.205, -0.129,  0.26 ],
       [-0.354,  0.886,  0.109, -0.011, -0.066, -0.263],
       [-0.354, -0.009, -0.273,  0.639,  0.343,  0.133],
       [-0.354, -0.032,  0.296,  0.122,  0.368,  0.468]])

In [39]:
QT = Q.T
QT

array([[-0.354, -0.354, -0.354, -0.354, -0.354, -0.354, -0.354, -0.354],
       [-0.261, -0.261,  0.026, -0.261, -0.089,  0.886, -0.009, -0.032],
       [ 0.782, -0.191, -0.284, -0.191, -0.247,  0.109, -0.273,  0.296],
       [-0.063,  0.385, -0.492, -0.375, -0.205, -0.011,  0.639,  0.122],
       [-0.167, -0.608, -0.255,  0.514, -0.129, -0.066,  0.343,  0.368],
       [-0.088, -0.318,  0.404, -0.596,  0.26 , -0.263,  0.133,  0.468]])

In [40]:
from numpy.linalg import norm

row0 = QT[0]
row1 = QT[1]
row2 = QT[2]
row3 = QT[3]
row4 = QT[4]
row5 = QT[5]

norm(row0), norm(row1), norm(row2), norm(row3), norm(row4), norm(row5)

(0.9999999999999999,
 1.0,
 1.0000000000000002,
 0.9999999999999999,
 1.0000000000000002,
 0.9999999999999999)

In [42]:
row0@row1, row0@row2, row1@row2, row3@row2, row5@row1, row4@row5

(-5.551115123125783e-17,
 1.3877787807814457e-16,
 1.3183898417423734e-16,
 3.469446951953614e-16,
 5.551115123125783e-17,
 -8.326672684688674e-17)

In [43]:
QT@Q

array([[ 1.000e+00, -5.551e-17,  1.284e-16, -6.939e-18, -5.730e-17,
        -8.153e-17],
       [-5.551e-17,  1.000e+00,  1.388e-16,  3.469e-17,  6.685e-17,
         8.749e-17],
       [ 1.284e-16,  1.388e-16,  1.000e+00,  3.608e-16,  2.496e-16,
        -1.389e-16],
       [-6.939e-18,  3.469e-17,  3.608e-16,  1.000e+00,  9.656e-17,
        -1.840e-16],
       [-5.730e-17,  6.685e-17,  2.496e-16,  9.656e-17,  1.000e+00,
        -8.395e-17],
       [-8.153e-17,  8.749e-17, -1.389e-16, -1.840e-16, -8.395e-17,
         1.000e+00]])

In [44]:
b = np.array(ys)

In [45]:
b

array([21.6, 17.2,  4.7,  9.6, 15.7, 26.8, 25.5, 22.4])

In [47]:
xhat = Rinv@QT@b
xhat

array([ 3.767, 11.081,  8.961,  8.015,  5.609, -0.347])