### <center>San Jose State University<br>Department of Applied Data Science</center>
#  <center>DATA 220<br>Mathematical Methods for Data Analysis</center>
### <center>Fall 2020<br>Instructor: Ron Mak</center>
#  <center>Assignment #11<br>Matrix Operations Problem Set</center>
#### <center>100 points total (20 points each)<br><br>Work together with your lab partner.<br>Write your solutions in one or more cells after each problem.<br>Whenever possible, use matrix operations and not loops.<br>You can add your own functions or other support code.</center>
#### <center>Due November 19, 2020</center>

#### <strong>PROBLEM 1.</strong> Amalgamated Widgets, Inc. manufactures several products using various amounts of materials per product:
<table>
    <tr>
        <th>Product</th>
        <th>Metal</th>
        <th>Wood</th>
        <th>Plastic</th>
        <th>Cloth</th>
        <th>Paper</th>
    </tr>
    <tr>
        <td>A</td><td>0</td><td>1.3</td><td>0.2</td><td>0.8</td><td>0.4</td>
    </tr>
    <tr>
        <td>B</td><td>0</td><td>0</td><td>1.5</td><td>0.4</td><td>0.3</td>
    </tr>
    <tr>
        <td>C</td><td>0.25</td><td>0</td><td>0</td><td>0.2</td><td>0.7</td>
    </tr>
    <tr>
        <td>D</td><td>0</td><td>0</td><td>0.3</td><td>0.7</td><td>0.5</td>
    </tr>
    <tr>
        <td>E</td><td>0.15</td><td>0</td><td>0.5</td><td>0.4</td><td>0.8</td>
    </tr>
</table>

#### On a certain day, the following total amounts of materials were used:
<table>
    <tr>
        <th>Metal</th>
        <th>Wood</th>
        <th>Plastic</th>
        <th>Cloth</th>
        <th>Paper</th>
    </tr>
    <tr>
        <td>51.0</td><td>312.0</td><td>215.4</td><td>373.1</td><td>356.0</td>
    </tr>
</table>

#### How many of each product were made that day?

In [21]:
import numpy as np

'''
x1s = [   0,       0,    0.25,       0,  0.15]  # Metal
x2s = [ 1.3,       0,       0,       0,     0]  # Wood
x3s = [ 0.2,     1.5,       0,     0.3,   0.5]  # Plastic
x4s = [ 0.8,     0.4,     0.2,     0.7,   0.4]  # Cloth
x5s = [ 0.4,     0.3,     0.7,     0.5,   0.8]  # Paper
ys  = [51.0,   312.0,    215.4,  373.1, 356.0]  # Quantities 
'''

'''x1s = [0, 1.3, 0.2, 0.8, 0.4]
x2s = [0, 0, 1.5, 0.4, 0.3]
x3s = [0.25, 0, 0, 0.2, 0.7]
x4s = [0, 0, 0.3, 0.7, 0.5]
x5s = [0.15, 0, 0.5, 0.4, 0.8]
ys  = [51.0, 312.0, 215.4, 373.1, 356.0]  # Quantities 
'''

'''
0x1 + 0x1 + 0.25x1 + 0x1 + 0.15x1 = 51
'''
x1s = [   0,       0,    0.25,       0,  0.15]  # Metal
x2s = [ 1.3,       0,       0,       0,     0]  # Wood
x3s = [ 0.2,     1.5,       0,     0.3,   0.5]  # Plastic
x4s = [ 0.8,     0.4,     0.2,     0.7,   0.4]  # Cloth
x5s = [ 0.4,     0.3,     0.7,     0.5,   0.8]  # Paper
ys  = [[51.0],   
       [312.0],    
       [215.4],  
       [373.1], 
        [356.0]]  # Quantities 



x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)

y.reshape(1,5)
y

array([[ 51. ],
       [312. ],
       [215.4],
       [373.1],
       [356. ]])

In [22]:
n        = len(ys)
sum_x1   = np.sum(x1)
sum_x2   = np.sum(x2)
sum_x3   = np.sum(x3)
sum_x4   = np.sum(x4)
sum_x5   = np.sum(x5)

sum_y    = np.sum(y)
sum_x1y  = np.sum(x1*y)
sum_x2y  = np.sum(x2*y)
sum_x3y  = np.sum(x3*y)
sum_x4y  = np.sum(x4*y)
sum_x5y  = np.sum(x5*y)


sum_x1x1 = np.sum(x1*x1)
sum_x2x2 = np.sum(x2*x2)
sum_x3x3 = np.sum(x3*x3)
sum_x4x4 = np.sum(x4*x4)
sum_x5x5 = np.sum(x5*x5)

sum_x1x2 = np.sum(x1*x2)
sum_x1x3 = np.sum(x1*x3)
sum_x1x4 = np.sum(x1*x4)
sum_x1x5 = np.sum(x1*x5)

sum_x2x3 = np.sum(x2*x3)
sum_x2x4 = np.sum(x2*x4)
sum_x2x5 = np.sum(x2*x5)

sum_x3x4 = np.sum(x3*x4)
sum_x3x5 = np.sum(x3*x5)

sum_x4x5 = np.sum(x4*x5)


n, sum_x1, sum_x2, sum_x3, sum_x4, sum_x5, sum_y, sum_x1y, sum_x2y, sum_x3y, sum_x4y, sum_x5y, sum_x1x1, sum_x2x2,sum_x3x3, sum_x4x4, sum_x5x5,  sum_x1x2, sum_x1x3, sum_x1x4, sum_x1x5, sum_x2x3, sum_x2x4, sum_x2x5, sum_x3x4, sum_x3x5, sum_x4x5

(5,
 0.4,
 1.3,
 2.5,
 2.5,
 2.7,
 1307.5,
 523.0,
 1699.75,
 3268.75,
 3268.7500000000005,
 3530.25,
 0.08499999999999999,
 1.6900000000000002,
 2.63,
 1.4900000000000002,
 1.6300000000000001,
 0.0,
 0.075,
 0.11,
 0.295,
 0.26,
 1.04,
 0.52,
 1.1700000000000002,
 1.08,
 1.25)

In [23]:
eqn1 = np.array([n, sum_x1, sum_x2, sum_x3, sum_x4, sum_x5, sum_y])
eqn2 = np.array([sum_x1, sum_x1x1, sum_x1x2, sum_x1x3, sum_x1x4, sum_x1x5, sum_x1y])
eqn3 = np.array([sum_x2, sum_x1x2, sum_x2x2, sum_x2x3, sum_x2x4, sum_x2x5, sum_x2y])
eqn4 = np.array([sum_x3, sum_x1x3, sum_x2x3, sum_x3x3, sum_x3x4, sum_x3x5, sum_x3y])
eqn5 = np.array([sum_x4, sum_x1x4, sum_x2x4, sum_x3x4, sum_x4x4, sum_x4x5, sum_x4y])
eqn6 = np.array([sum_x5, sum_x1x5, sum_x2x5, sum_x3x5, sum_x4x5, sum_x5x5, sum_x5y])

eqn1, eqn2, eqn3, eqn4, eqn5, eqn6

(array([5.0000e+00, 4.0000e-01, 1.3000e+00, 2.5000e+00, 2.5000e+00,
        2.7000e+00, 1.3075e+03]),
 array([4.00e-01, 8.50e-02, 0.00e+00, 7.50e-02, 1.10e-01, 2.95e-01,
        5.23e+02]),
 array([1.30000e+00, 0.00000e+00, 1.69000e+00, 2.60000e-01, 1.04000e+00,
        5.20000e-01, 1.69975e+03]),
 array([2.50000e+00, 7.50000e-02, 2.60000e-01, 2.63000e+00, 1.17000e+00,
        1.08000e+00, 3.26875e+03]),
 array([2.50000e+00, 1.10000e-01, 1.04000e+00, 1.17000e+00, 1.49000e+00,
        1.25000e+00, 3.26875e+03]),
 array([2.70000e+00, 2.95000e-01, 5.20000e-01, 1.08000e+00, 1.25000e+00,
        1.63000e+00, 3.53025e+03]))

In [18]:
import numpy as np
'''
A = np.array([[5.0000e+00, 2.7000e+00, 2.2000e+00, 1.1500e+00, 1.5000e+00,1.8500e+00],
              [2.7000e+00, 2.5300e+00, 7.4000e-01, 4.4000e-01, 8.2000e-01, 7.4000e-01],
              [2.2000e+00, 7.4000e-01, 2.5000e+00, 2.9000e-01, 8.8000e-01, 1.1500e+00],
              [1.1500e+00, 4.4000e-01, 2.9000e-01, 5.9250e-01, 4.9000e-01, 6.7750e-01],
              [1.5000e+00, 8.2000e-01, 8.8000e-01, 4.9000e-01, 8.3000e-01, 8.3000e-01],
              [1.85  ,   0.74  ,   1.15  ,   0.6775,   0.83  ,   1.0725]
             ])

b = np.array([[1.3075e+03],
             [8.8956e+02], 
             [5.7914e+02], 
             [3.3657e+02], 
             [5.0379e+02], 
             [549.39]])
'''

A = np.array([[5.0000e+00, 4.0000e-01, 1.3000e+00, 2.5000e+00, 2.5000e+00,
        2.7000e+00],
              [4.00e-01, 8.50e-02, 0.00e+00, 7.50e-02, 1.10e-01, 2.95e-01],
              [2.2000e+00, 7.4000e-01, 2.5000e+00, 2.9000e-01, 8.8000e-01, 1.1500e+00],
              [1.1500e+00, 4.4000e-01, 2.9000e-01, 5.9250e-01, 4.9000e-01, 6.7750e-01],
              [1.5000e+00, 8.2000e-01, 8.8000e-01, 4.9000e-01, 8.3000e-01, 8.3000e-01],
              [1.85  ,   0.74  ,   1.15  ,   0.6775,   0.83  ,   1.0725]
             ])

b = np.array([ ])



solution = np.linalg.solve(A, b)


'''
print(f'β0 = {solution[0]:9,.2f}')
print(f'β1 = {solution[1]:9,.2f}')
print(f'β2 = {solution[2]:9,.2f}')
print(f'β3 = {solution[3]:9,.2f}')
print(f'β4 = {solution[4]:9,.2f}')
print(f'β5 = {solution[5]:9,.2f}')
'''

"\nprint(f'β0 = {solution[0]:9,.2f}')\nprint(f'β1 = {solution[1]:9,.2f}')\nprint(f'β2 = {solution[2]:9,.2f}')\nprint(f'β3 = {solution[3]:9,.2f}')\nprint(f'β4 = {solution[4]:9,.2f}')\nprint(f'β5 = {solution[5]:9,.2f}')\n"

In [ ]:
import numpy as np

xs = [1,2,3,4,5]
ys = [1,2,4,4,6]

b = np.array(ys)
ones = np.array([1 for _ in range(len(xs))])

In [ ]:
A = np.array([ones, np.array(xs)]).T
A

In [ ]:
A.T

In [ ]:
ATA = A.T@A
ATA

In [ ]:
from numpy.linalg import inv
%precision 3

ATAinv = inv(ATA)
ATAinv

In [ ]:
ATb = A.T@b
ATb

In [ ]:
xhat = ATAinv@ATb
xhat

Therefore, b = -0.2 and m = 1.2

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

x = np.array([1,2,3,4,5])
y = np.array([1,2,4,4,6])


intercept, slope = xhat

abline_values = [slope * i + intercept for i in x]

plt.scatter(x, y)
plt.plot(x, abline_values, 'b')
plt.title(f'intercept = {intercept:.1f}, m= {slope:.1f}')
plt.show()


#### <strong>PROBLEM 3.</strong> The following table shows the mean distances <em>x</em> in astonomical units (multiples of the distance between the sun and the earth) and the periods <em>y</em> in years (how many earth-years to orbit the sun):
<table>
    <tr>
        <th>Planet</th>
        <th>Mercury</th>
        <th>Venus</th>
        <th>Earth</th>
        <th>Mars</th>
        <th>Jupiter</th>
        <th>Saturn</th>
    </tr>
    <tr>
        <td>Distance </em>x</em></td><td>0.387</td><td>0.723</td><td>1.000</td><td>1.524</td><td>5.203</td><td>9.537</td>
    </tr>
    <tr>
        <td>Years </em>y</em></td><td>0.241</td><td>0.615</td><td>1.000</td><td>1.881</td><td>11.862</td><td>29.457</td>
    </tr>
</table>

#### It turns out that if you take the natural logarithm of the numbers in the table, the transformed points lie roughly in a straight line. Find the least-squares regression line using the matrix form of the normal equations <em>A.T</em>@<em>A</em>@<strong>x</strong> = <em>A.T</em>@<strong>b</strong>. 

In [ ]:
import numpy as np

xs = [0.387,0.723,1.000,1.524,5.203,9.537]
ys = [0.241,0.615,1.000,1.881,11.862,29.457]

b = np.array(ys)
ones = np.array([1 for _ in range(len(xs))])

In [ ]:
A = np.array([ones, np.array(xs)]).T
A

In [ ]:
A.T

In [ ]:
ATA = A.T@A
ATA

In [ ]:
from numpy.linalg import inv
%precision 3

ATAinv = inv(ATA)
ATAinv

In [ ]:
ATb = A.T@b
ATb

In [ ]:
xhat = ATAinv@ATb
xhat

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

x = np.array([0.387,0.723,1.000,1.524,5.203,9.537])
y = np.array([0.241,0.615,1.000,1.881,11.862,29.457])


# Find the slope and intercept of the best fit line
intercept, slope = xhat

# Create a list of values in the best fit line
abline_values = [slope * i + intercept for i in x]

# Plot the best fit line over the actual values
plt.scatter(x, y)
plt.plot(x, abline_values, 'b')
plt.title(f'intercept = {intercept:.3f}, m= {slope:.3f}')
plt.show()


#### <strong>PROBLEM 4.a.</strong> Here's more data about that certain day at Amalgamated Widgets, Inc. There are three more products and the cost  to make one of each product.
<table>
    <tr>
        <th>Product</th>
        <th>Metal</th>
        <th>Wood</th>
        <th>Plastic</th>
        <th>Cloth</th>
        <th>Paper</th>
        <th>Cost</th>
    </tr>
    <tr>
        <td>A</td><td>0</td><td>1.3</td><td>0.2</td><td>0.8</td><td>0.4</td><td>21.60</td>
    </tr>
    <tr>
        <td>B</td><td>0</td><td>0</td><td>1.5</td><td>0.4</td><td>0.3</td><td>17.20</td>
    </tr>
    <tr>
        <td>C</td><td>0.25</td><td>0</td><td>0</td><td>0.2</td><td>0.7</td><td>4.70</td>
    </tr>
    <tr>
        <td>D</td><td>0</td><td>0</td><td>0.3</td><td>0.7</td><td>0.5</td><td>9.60</td>
    </tr>
    <tr>
        <td>E</td><td>0.15</td><td>0</td><td>0.5</td><td>0.4</td><td>0.8</td><td>15.70</td>
    </tr>
    <tr>
        <td>F</td><td>1.00</td><td>0.90</td><td>0.00</td><td>0.65</td><td>0.00</td><td>26.80</td>
    </tr>
    <tr>
        <td>G</td><td>0.22</td><td>0.00</td><td>1.80</td><td>1.00</td><td>1.25</td><td>25.50</td>
    </tr>
    <tr>
        <td>H</td><td>0.20</td><td>0.75</td><td>0.65</td><td>1.00</td><td>1.25</td><td>22.40</td>
    </tr>
</table>

#### The manufacturing cost of a product is related to the amounts of materials used to make the product. Find the least-squares regression line using the matrix form of the normal equations <em>A.T</em>@<em>A</em>@<strong>x</strong> = <em>A.T</em>@<strong>b</strong> that will compute an estimated manufacturing cost of a product.

In [ ]:
import numpy as np
from numpy.linalg import inv
%precision 3

In [ ]:
x1s = [     0, 0, 0.25, 0, 0.15, 1.00, 0.22, 0.20]  # Metal
x2s = [   1.3, 0, 0, 0, 0, 0.90, 0.00, 0.75]  # Wood
x3s = [   0.2, 1.5, 0, 0.3, 0.5, 0.00, 1.80, 0.65]  # Plastic
x4s = [   0.8, 0.4, 0.2, 0.7, 0.4, 0.65, 1.00, 1.00]  # Cloth
x5s = [   0.4, 0.3, 0.7, 0.5, 0.8, 0.00, 1.25, 1.25]  # Paper
ys  = [ 21.60, 17.20, 4.70, 9.60, 15.70, 26.80, 25.50, 22.40]  # Cost

x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)

In [ ]:
ones = np.array([1, 1, 1, 1, 1, 1, 1, 1])
A = np.array([ones, x1, x2, x3, x4, x5]).T
A

In [ ]:
ATA = A.T@A
ATA

In [ ]:
b = y
ATb = A.T@b
ATb

In [ ]:
ATAinv = inv(ATA)
ATAinv

In [ ]:
xhat = ATAinv@ATb
xhat

#### We can see the answer is consistent

In [ ]:
A@xhat

In [ ]:
b

In [ ]:
for i, item in enumerate(xhat):
    print(f'β{i}: {item}')

#### <strong>PROBLEM 4.b.</strong> Find the least-squares regression line for the same data using <em>QR</em> factorization. Verify that matrix <em>R</em> is upper-triangular and invertible. Verify that the columns of matrix <em>Q</em> are orthonormal. 

In [ ]:
import numpy as np
from numpy.linalg import inv, qr

In [ ]:
x1s = [     0, 0, 0.25, 0, 0.15, 1.00, 0.22, 0.20]  # Metal
x2s = [   1.3, 0, 0, 0, 0, 0.90, 0.00, 0.75]  # Wood
x3s = [   0.2, 1.5, 0, 0.3, 0.5, 0.00, 1.80, 0.65]  # Plastic
x4s = [   0.8, 0.4, 0.2, 0.7, 0.4, 0.65, 1.00, 1.00]  # Cloth
x5s = [   0.4, 0.3, 0.7, 0.5, 0.8, 0.00, 1.25, 1.25]  # Paper
ys  = [ 21.60, 17.20, 4.70, 9.60, 15.70, 26.80, 25.50, 22.40]  # Cost

x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)

In [ ]:
ones = np.array([1, 1, 1, 1, 1, 1, 1, 1])
A = np.array([ones, x1, x2, x3, x4, x5]).T
A

In [ ]:
A

In [ ]:
Q,R = qr(A)
R

We can see that matrix R is also invertible

In [ ]:
Rinv = inv(R)
Rinv

In [ ]:
Q

In [ ]:
QT = Q.T
QT

In [ ]:
from numpy.linalg import norm

row0 = QT[0]
row1 = QT[1]
row2 = QT[2]
row3 = QT[3]
row4 = QT[4]
row5 = QT[5]

norm(row0), norm(row1), norm(row2), norm(row3), norm(row4), norm(row5)

In [ ]:
row0@row1, row0@row2, row1@row2, row3@row2, row5@row1, row4@row5

In [ ]:
QT@Q

In [ ]:
b = np.array(ys)

In [ ]:
b

In [ ]:
xhat = Rinv@QT@b
xhat

In [ ]:
for i, item in enumerate(xhat):
    print(f'β{i}: {item}')