### <center>San Jose State University<br>Department of Applied Data Science</center>
#  <center>DATA 220<br>Mathematical Methods for Data Analysis</center>
### <center>Fall 2020<br>Instructor: Ron Mak</center>
#  <center>Assignment #11<br>Matrix Operations Problem Set</center>
#### <center>100 points total (20 points each)<br><br>Work together with your lab partner.<br>Write your solutions in one or more cells after each problem.<br>Whenever possible, use matrix operations and not loops.<br>You can add your own functions or other support code.</center>
#### <center>Due November 19, 2020</center>

#### <strong>PROBLEM 1.</strong> Amalgamated Widgets, Inc. manufactures several products using various amounts of materials per product:
<table>
    <tr>
        <th>Product</th>
        <th>Metal</th>
        <th>Wood</th>
        <th>Plastic</th>
        <th>Cloth</th>
        <th>Paper</th>
    </tr>
    <tr>
        <td>A</td><td>0</td><td>1.3</td><td>0.2</td><td>0.8</td><td>0.4</td>
    </tr>
    <tr>
        <td>B</td><td>0</td><td>0</td><td>1.5</td><td>0.4</td><td>0.3</td>
    </tr>
    <tr>
        <td>C</td><td>0.25</td><td>0</td><td>0</td><td>0.2</td><td>0.7</td>
    </tr>
    <tr>
        <td>D</td><td>0</td><td>0</td><td>0.3</td><td>0.7</td><td>0.5</td>
    </tr>
    <tr>
        <td>E</td><td>0.15</td><td>0</td><td>0.5</td><td>0.4</td><td>0.8</td>
    </tr>
</table>

#### On a certain day, the following total amounts of materials were used:
<table>
    <tr>
        <th>Metal</th>
        <th>Wood</th>
        <th>Plastic</th>
        <th>Cloth</th>
        <th>Paper</th>
    </tr>
    <tr>
        <td>51.0</td><td>312.0</td><td>215.4</td><td>373.1</td><td>356.0</td>
    </tr>
</table>

#### How many of each product were made that day?

In [10]:
import numpy as np

x1s = [   0,       0,    0.25,       0,  0.15]  # Metal
x2s = [ 1.3,       0,       0,       0,     0]  # Wood
x3s = [ 0.2,     1.5,       0,     0.3,   0.5]  # Plastic
x4s = [ 0.8,     0.4,     0.2,     0.7,   0.4]  # Cloth
x5s = [ 0.4,     0.3,     0.7,     0.5,   0.8]  # Paper
ys  = [51.0,   312.0,    215.4,  373.1, 356.0]  # Quantities 


x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)



In [11]:
n        = len(ys)
sum_x1   = np.sum(x1)
sum_x2   = np.sum(x2)
sum_x3   = np.sum(x3)
sum_x4   = np.sum(x4)
sum_x5   = np.sum(x5)

sum_y    = np.sum(y)
sum_x1y  = np.sum(x1*y)
sum_x2y  = np.sum(x2*y)
sum_x3y  = np.sum(x3*y)
sum_x4y  = np.sum(x4*y)
sum_x5y  = np.sum(x5*y)


sum_x1x1 = np.sum(x1*x1)
sum_x2x2 = np.sum(x2*x2)
sum_x3x3 = np.sum(x3*x3)
sum_x4x4 = np.sum(x4*x4)
sum_x5x5 = np.sum(x5*x5)

sum_x1x2 = np.sum(x1*x2)
sum_x1x3 = np.sum(x1*x3)
sum_x1x4 = np.sum(x1*x4)
sum_x1x5 = np.sum(x1*x5)

sum_x2x3 = np.sum(x2*x3)
sum_x2x4 = np.sum(x2*x4)
sum_x2x5 = np.sum(x2*x5)

sum_x3x4 = np.sum(x3*x4)
sum_x3x5 = np.sum(x3*x5)

sum_x4x5 = np.sum(x4*x5)


n, sum_x1, sum_x2, sum_x3, sum_x4, sum_x5, sum_y, sum_x1y, sum_x2y, sum_x3y, sum_x4y, sum_x5y, sum_x1x1, sum_x2x2,sum_x3x3, sum_x4x4, sum_x5x5,  sum_x1x2, sum_x1x3, sum_x1x4, sum_x1x5, sum_x2x3, sum_x2x4, sum_x2x5, sum_x3x4, sum_x3x5, sum_x4x5

(5,
 0.4,
 1.3,
 2.5,
 2.5,
 2.7,
 1307.5,
 107.25,
 66.3,
 768.13,
 612.25,
 736.13,
 0.08499999999999999,
 1.6900000000000002,
 2.63,
 1.4900000000000002,
 1.6300000000000001,
 0.0,
 0.075,
 0.11,
 0.295,
 0.26,
 1.04,
 0.52,
 1.1700000000000002,
 1.08,
 1.25)

In [12]:
#eqn1 = np.array([n, sum_x1, sum_x2, sum_x3, sum_x4, sum_x5, sum_y])
#eqn2 = np.array([sum_x1, sum_x1x1, sum_x1x2, sum_x1x3, sum_x1x4, sum_x1x5, sum_x1y])
#eqn3 = np.array([sum_x2, sum_x1x2, sum_x2x3, sum_x2x4, sum_x2x5, sum_x2x2, sum_x2y])
#eqn4 = np.array([sum_x3, sum_x1x3, sum_x2x3, sum_x3x4, sum_x3x5, sum_x3x3, sum_x3y])
#eqn5 = np.array([sum_x4, sum_x1x4, sum_x2x4, sum_x3x4, sum_x4x5, sum_x4x4, sum_x4y])
#eqn6 = np.array([sum_x5, sum_x1x5, sum_x2x5, sum_x3x5, sum_x4x5, sum_x5x5, sum_x5y])

eqn1 = np.array([n, sum_x1, sum_x2, sum_x3, sum_x4, sum_x5, sum_y])
eqn2 = np.array([sum_x1, sum_x1x1, sum_x1x2, sum_x1x3, sum_x1x4, sum_x1x5, sum_x1y])
eqn3 = np.array([sum_x2, sum_x1x2, sum_x2x2, sum_x2x3, sum_x2x4, sum_x2x5, sum_x2y])
eqn4 = np.array([sum_x3, sum_x1x3, sum_x2x3, sum_x3x3, sum_x3x4, sum_x3x5, sum_x3y])
eqn5 = np.array([sum_x4, sum_x1x4, sum_x2x4, sum_x3x4, sum_x4x4, sum_x4x5, sum_x4y])
eqn6 = np.array([sum_x5, sum_x1x5, sum_x2x5, sum_x3x5, sum_x4x5, sum_x5x5, sum_x5y])


eqn1, eqn2, eqn3, eqn4, eqn5, eqn6

(array([5.000e+00, 4.000e-01, 1.300e+00, 2.500e+00, 2.500e+00, 2.700e+00,
        1.308e+03]),
 array([4.000e-01, 8.500e-02, 0.000e+00, 7.500e-02, 1.100e-01, 2.950e-01,
        1.072e+02]),
 array([ 1.3 ,  0.  ,  1.69,  0.26,  1.04,  0.52, 66.3 ]),
 array([2.500e+00, 7.500e-02, 2.600e-01, 2.630e+00, 1.170e+00, 1.080e+00,
        7.681e+02]),
 array([2.500e+00, 1.100e-01, 1.040e+00, 1.170e+00, 1.490e+00, 1.250e+00,
        6.122e+02]),
 array([2.700e+00, 2.950e-01, 5.200e-01, 1.080e+00, 1.250e+00, 1.630e+00,
        7.361e+02]))

In [13]:
import numpy as np

A = np.array([[5.0000e+00, 4.0000e-01, 1.3000e+00, 2.5000e+00, 2.5000e+00, 2.7000e+00],
              [4.0000e-01, 8.5000e-02, 0.0000e+00, 7.5000e-02, 1.1000e-01, 2.9500e-01],
              [ 1.3 ,  0.  ,  0.26,  1.04,  0.52,  1.69],
              [2.5000e+00, 7.5000e-02, 2.6000e-01, 1.1700e+00, 1.0800e+00, 2.6300e+00],
              [2.5000e+00, 1.1000e-01, 1.0400e+00, 1.1700e+00, 1.2500e+00, 1.4900e+00],
              [2.7000e+00, 2.9500e-01, 5.2000e-01, 1.0800e+00, 1.2500e+00, 1.6300e+00]
             ])


b = np.array([1.3075e+03, 1.0725e+02, 66.3, 7.6813e+02, 6.1225e+02, 7.3613e+02])

#Ainv = np.linalg.inv(A)

#solution = np.linalg.solve(Ainv, b)
solution = np.linalg.inv(A)@b


print(f'β0 = {solution[0]:9,.2f}')
print(f'β1 = {solution[1]:9,.2f}')
print(f'β2 = {solution[2]:9,.2f}')
print(f'β3 = {solution[3]:9,.2f}')
print(f'β4 = {solution[4]:9,.2f}')
print(f'β5 = {solution[5]:9,.2f}')


β0 =  1,293.54
β1 = -2,426.11
β2 =   -624.76
β3 =   -532.12
β4 =   -365.59
β5 =   -419.73


In [27]:
A@solution

array([  -85.441,   223.205,   320.077,   668.121,   181.538, -1932.494,
       -1088.279,  -896.392])

In [1]:
import numpy as np
from numpy.linalg import inv
%precision 3

'%.3f'

In [4]:
x1s = [   0,       0,    0.25,       0,  0.15]  # Metal
x2s = [ 1.3,       0,       0,       0,     0]  # Wood
x3s = [ 0.2,     1.5,       0,     0.3,   0.5]  # Plastic
x4s = [ 0.8,     0.4,     0.2,     0.7,   0.4]  # Cloth
x5s = [ 0.4,     0.3,     0.7,     0.5,   0.8]  # Paper
ys  = [51.0,   312.0,    215.4,  373.1, 356.0]  # Quantities 


x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)

In [5]:
ones = np.array([1, 1, 1, 1, 1])
A = np.array([ones, x1, x2, x3, x4, x5]).T
A

array([[1.  , 0.  , 1.3 , 0.2 , 0.8 , 0.4 ],
       [1.  , 0.  , 0.  , 1.5 , 0.4 , 0.3 ],
       [1.  , 0.25, 0.  , 0.  , 0.2 , 0.7 ],
       [1.  , 0.  , 0.  , 0.3 , 0.7 , 0.5 ],
       [1.  , 0.15, 0.  , 0.5 , 0.4 , 0.8 ]])

In [6]:
ATA = A.T@A
ATA

array([[5.   , 0.4  , 1.3  , 2.5  , 2.5  , 2.7  ],
       [0.4  , 0.085, 0.   , 0.075, 0.11 , 0.295],
       [1.3  , 0.   , 1.69 , 0.26 , 1.04 , 0.52 ],
       [2.5  , 0.075, 0.26 , 2.63 , 1.17 , 1.08 ],
       [2.5  , 0.11 , 1.04 , 1.17 , 1.49 , 1.25 ],
       [2.7  , 0.295, 0.52 , 1.08 , 1.25 , 1.63 ]])

In [7]:
b = y
ATb = A.T@b
ATb

array([1307.5 ,  107.25,   66.3 ,  768.13,  612.25,  736.13])

In [8]:
ATAinv = inv(ATA)
ATAinv

array([[-2.833e+15,  1.281e+16, -4.689e+14,  9.351e+14,  5.057e+15,
        -1.974e+15],
       [ 1.281e+16, -5.796e+16,  2.121e+15, -4.230e+15, -2.287e+16,
         8.930e+15],
       [-4.689e+14,  2.121e+15, -7.761e+13,  1.548e+14,  8.369e+14,
        -3.267e+14],
       [ 9.351e+14, -4.230e+15,  1.548e+14, -3.087e+14, -1.669e+15,
         6.516e+14],
       [ 5.057e+15, -2.287e+16,  8.369e+14, -1.669e+15, -9.025e+15,
         3.524e+15],
       [-1.974e+15,  8.930e+15, -3.267e+14,  6.516e+14,  3.524e+15,
        -1.376e+15]])

In [9]:
xhat = ATAinv@ATb
xhat

array([-1024.,  4096.,  -368.,   384.,  1280.,   320.])

#### We can see the answer is consistent

In [15]:
A@xhat

array([1064.  ,  202.56,  178.88,  324.8 ,   33.92,  788.48])

In [16]:
b

array([1307.5 ,  107.25,   66.3 ,  768.13,  612.25,  736.13])

In [14]:
for i, item in enumerate(xhat):
    print(f'β{i}: {item}')

β0: -1024.0
β1: 4096.0
β2: -368.0
β3: 384.0
β4: 1280.0
β5: 320.0


#### <strong>PROBLEM 2.</strong> Find the least-squares regression line for the points (1,1), (2,2), (3,4), (4,4), and (5,6) using the matrix form of the normal equations <em>A.T</em>@<em>A</em>@<strong>x</strong> = <em>A.T</em>@<strong>b</strong>.

In [ ]:
import numpy as np

xs = [1,2,3,4,5]
ys = [1,2,4,4,6]

b = np.array(ys)
ones = np.array([1 for _ in range(len(xs))])

In [ ]:
A = np.array([ones, np.array(xs)]).T
A

In [ ]:
A.T

In [ ]:
ATA = A.T@A
ATA

In [ ]:
from numpy.linalg import inv
%precision 3

ATAinv = inv(ATA)
ATAinv

In [ ]:
ATb = A.T@b
ATb

In [ ]:
xhat = ATAinv@ATb
xhat

Therefore, b = -0.2 and m = 1.2

#### <strong>PROBLEM 3.</strong> The following table shows the mean distances <em>x</em> in astonomical units (multiples of the distance between the sun and the earth) and the periods <em>y</em> in years (how many earth-years to orbit the sun):
<table>
    <tr>
        <th>Planet</th>
        <th>Mercury</th>
        <th>Venus</th>
        <th>Earth</th>
        <th>Mars</th>
        <th>Jupiter</th>
        <th>Saturn</th>
    </tr>
    <tr>
        <td>Distance </em>x</em></td><td>0.387</td><td>0.723</td><td>1.000</td><td>1.524</td><td>5.203</td><td>9.537</td>
    </tr>
    <tr>
        <td>Years </em>y</em></td><td>0.241</td><td>0.615</td><td>1.000</td><td>1.881</td><td>11.862</td><td>29.457</td>
    </tr>
</table>

#### It turns out that if you take the natural logarithm of the numbers in the table, the transformed points lie roughly in a straight line. Find the least-squares regression line using the matrix form of the normal equations <em>A.T</em>@<em>A</em>@<strong>x</strong> = <em>A.T</em>@<strong>b</strong>. 

In [ ]:
import numpy as np

xs = [0.387,0.723,1.000,1.524,5.203,9.537]
ys = [0.241,0.615,1.000,1.881,11.862,29.457]

b = np.array(ys)
ones = np.array([1 for _ in range(len(xs))])

In [ ]:
A = np.array([ones, np.array(xs)]).T
A

In [ ]:
A.T

In [ ]:
ATA = A.T@A
ATA

In [ ]:
from numpy.linalg import inv
%precision 3

ATAinv = inv(ATA)
ATAinv

In [ ]:
ATb = A.T@b
ATb

In [ ]:
xhat = ATAinv@ATb
xhat

#### <strong>PROBLEM 4.a.</strong> Here's more data about that certain day at Amalgamated Widgets, Inc. There are three more products and the cost  to make one of each product.
<table>
    <tr>
        <th>Product</th>
        <th>Metal</th>
        <th>Wood</th>
        <th>Plastic</th>
        <th>Cloth</th>
        <th>Paper</th>
        <th>Cost</th>
    </tr>
    <tr>
        <td>A</td><td>0</td><td>1.3</td><td>0.2</td><td>0.8</td><td>0.4</td><td>21.60</td>
    </tr>
    <tr>
        <td>B</td><td>0</td><td>0</td><td>1.5</td><td>0.4</td><td>0.3</td><td>17.20</td>
    </tr>
    <tr>
        <td>C</td><td>0.25</td><td>0</td><td>0</td><td>0.2</td><td>0.7</td><td>4.70</td>
    </tr>
    <tr>
        <td>D</td><td>0</td><td>0</td><td>0.3</td><td>0.7</td><td>0.5</td><td>9.60</td>
    </tr>
    <tr>
        <td>E</td><td>0.15</td><td>0</td><td>0.5</td><td>0.4</td><td>0.8</td><td>15.70</td>
    </tr>
    <tr>
        <td>F</td><td>1.00</td><td>0.90</td><td>0.00</td><td>0.65</td><td>0.00</td><td>26.80</td>
    </tr>
    <tr>
        <td>G</td><td>0.22</td><td>0.00</td><td>1.80</td><td>1.00</td><td>1.25</td><td>25.50</td>
    </tr>
    <tr>
        <td>H</td><td>0.20</td><td>0.75</td><td>0.65</td><td>1.00</td><td>1.25</td><td>22.40</td>
    </tr>
</table>

#### The manufacturing cost of a product is related to the amounts of materials used to make the product. Find the least-squares regression line using the matrix form of the normal equations <em>A.T</em>@<em>A</em>@<strong>x</strong> = <em>A.T</em>@<strong>b</strong> that will compute an estimated manufacturing cost of a product.

In [17]:
import numpy as np
from numpy.linalg import inv
%precision 3

'%.3f'

In [18]:
x1s = [     0, 0, 0.25, 0, 0.15, 1.00, 0.22, 0.20]  # Metal
x2s = [   1.3, 0, 0, 0, 0, 0.90, 0.00, 0.75]  # Wood
x3s = [   0.2, 1.5, 0, 0.3, 0.5, 0.00, 1.80, 0.65]  # Plastic
x4s = [   0.8, 0.4, 0.2, 0.7, 0.4, 0.65, 1.00, 1.00]  # Cloth
x5s = [   0.4, 0.3, 0.7, 0.5, 0.8, 0.00, 1.25, 1.25]  # Paper
ys  = [ 21.60, 17.20, 4.70, 9.60, 15.70, 26.80, 25.50, 22.40]  # Cost

x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)

In [19]:
ones = np.array([1, 1, 1, 1, 1, 1, 1, 1])
A = np.array([ones, x1, x2, x3, x4, x5]).T
A

array([[1.  , 0.  , 1.3 , 0.2 , 0.8 , 0.4 ],
       [1.  , 0.  , 0.  , 1.5 , 0.4 , 0.3 ],
       [1.  , 0.25, 0.  , 0.  , 0.2 , 0.7 ],
       [1.  , 0.  , 0.  , 0.3 , 0.7 , 0.5 ],
       [1.  , 0.15, 0.  , 0.5 , 0.4 , 0.8 ],
       [1.  , 1.  , 0.9 , 0.  , 0.65, 0.  ],
       [1.  , 0.22, 0.  , 1.8 , 1.  , 1.25],
       [1.  , 0.2 , 0.75, 0.65, 1.  , 1.25]])

In [20]:
ATA = A.T@A
ATA

array([[8.   , 1.82 , 2.95 , 4.95 , 5.15 , 5.2  ],
       [1.82 , 1.173, 1.05 , 0.601, 1.18 , 0.82 ],
       [2.95 , 1.05 , 3.062, 0.748, 2.375, 1.458],
       [4.95 , 0.601, 0.748, 6.293, 3.62 , 4.143],
       [5.15 , 1.18 , 2.375, 3.62 , 3.913, 3.75 ],
       [5.2  , 0.82 , 1.458, 4.143, 3.75 , 4.755]])

In [21]:
b = y
ATb = A.T@b
ATb

array([143.5  ,  40.42 ,  69.   , 101.31 , 103.42 ,  94.325])

In [22]:
ATAinv = inv(ATA)
ATAinv

array([[ 1.008, -0.494, -0.037, -0.087, -0.752, -0.337],
       [-0.494,  1.678,  0.027,  0.221, -0.511,  0.453],
       [-0.037,  0.027,  1.493,  0.574, -2.102,  0.736],
       [-0.087,  0.221,  0.574,  0.639, -1.001,  0.113],
       [-0.752, -0.511, -2.102, -1.001,  5.226, -1.695],
       [-0.337,  0.453,  0.736,  0.113, -1.695,  1.513]])

In [23]:
xhat = ATAinv@ATb
xhat

array([ 3.767, 11.081,  8.961,  8.015,  5.609, -0.347])

#### We can see the answer is consistent

In [24]:
A@xhat

array([21.368, 17.93 ,  7.417,  9.925, 11.403, 26.56 , 25.808, 23.09 ])

In [25]:
b

array([21.6, 17.2,  4.7,  9.6, 15.7, 26.8, 25.5, 22.4])

In [26]:
for i, item in enumerate(xhat):
    print(f'β{i}: {item}')

β0: 3.7673014300317007
β1: 11.081421494512252
β2: 8.961425621985484
β3: 8.015336732811988
β4: 5.608681811607141
β5: -0.3468139042921692


#### <strong>PROBLEM 4.b.</strong> Find the least-squares regression line for the same data using <em>QR</em> factorization. Verify that matrix <em>R</em> is upper-triangular and invertible. Verify that the columns of matrix <em>Q</em> are orthonormal. 

In [ ]:
import numpy as np
from numpy.linalg import inv, qr

In [ ]:
x1s = [     0, 0, 0.25, 0, 0.15, 1.00, 0.22, 0.20]  # Metal
x2s = [   1.3, 0, 0, 0, 0, 0.90, 0.00, 0.75]  # Wood
x3s = [   0.2, 1.5, 0, 0.3, 0.5, 0.00, 1.80, 0.65]  # Plastic
x4s = [   0.8, 0.4, 0.2, 0.7, 0.4, 0.65, 1.00, 1.00]  # Cloth
x5s = [   0.4, 0.3, 0.7, 0.5, 0.8, 0.00, 1.25, 1.25]  # Paper
ys  = [ 21.60, 17.20, 4.70, 9.60, 15.70, 26.80, 25.50, 22.40]  # Cost

x1 = np.array(x1s)
x2 = np.array(x2s)
x3 = np.array(x3s)
x4 = np.array(x4s)
x5 = np.array(x5s)
y  = np.array(ys)

In [ ]:
ones = np.array([1, 1, 1, 1, 1, 1, 1, 1])
A = np.array([ones, x1, x2, x3, x4, x5]).T
A

In [ ]:
A

In [ ]:
Q,R = qr(A)
R

We can see that matrix R is also invertible

In [ ]:
Rinv = inv(R)
Rinv

In [ ]:
Q

In [ ]:
QT = Q.T
QT

In [ ]:
from numpy.linalg import norm

row0 = QT[0]
row1 = QT[1]
row2 = QT[2]
row3 = QT[3]
row4 = QT[4]
row5 = QT[5]

norm(row0), norm(row1), norm(row2), norm(row3), norm(row4), norm(row5)

In [ ]:
row0@row1, row0@row2, row1@row2, row3@row2, row5@row1, row4@row5

In [ ]:
QT@Q

In [ ]:
b = np.array(ys)

In [ ]:
b

In [ ]:
xhat = Rinv@QT@b
xhat

In [ ]:
for i, item in enumerate(xhat):
    print(f'β{i}: {item}')